name: Hello-World
on: [pull_request]

jobs:
  build:
    name: Testing basic hello-world command
    runs-on: ubuntu-20.04
    steps:
      - name: clone-repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'
      - name: build-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
      - name: python-wheel
        run: |
          python setup.py bdist_wheel
      - name: alfred-install
        run: |
          python -m pip install dist/alfred*.whl
      - name: hello-world
        run: |
          python -m alfred hello
